### DISCUSSION TITLE
How to run on remote server?

### DISCUSSION THREAD

**Discussion by abdessalaam** [reworkd/AgentGPT#1094] [Q&A]
I am trying to run it on my remote server that already has some ports used by other docker containers. I have tried changing ports from 3000 to something else, and also then tried the same with 8080, 8000.... I have also amended localhost to the IP of my server, but I still can't make it work. It starts ok and then announces that the fronted should be available on localhost:3000.

I tried to ignore it and go to my server ip:new_port but it doesn't work.

Firewall is also open in case anyone asks :).

I would appreciate any advice! Thank you

**Comment by jasangill1** [comment]
Hello @bpawel-bclub you can update the docker--compose.yml to reflect these chances !!! Alternatively, you can run `docker-compose down` in the project that is using your containers then try running `./setup` again let me know if this works!!

**Comment by HolaBribon** [comment]
It should be like this:

NEXT_PUBLIC_BACKEND_URL="http://your_server_ip:8000"
NEXTAUTH_URL="http://your_server_ip:3000"
REWORKD_PLATFORM_FRONTEND_URL="http://your_server_ip:3000"

**Comment by abdessalaam** [comment]
Thank you! I managed to make it work, though only in development (production didn't work), with the following:

```
version: '3.9'

services:
  next:
    container_name: next
    build:
      context: ./next
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Change to a different port, e.g., 3001
    volumes:
      - ./next/.env:/next/.env
      - ./next/:/next/
      - /next/node_modules
      - /next/.next

  platform:
    container_name: platform
    build:
      context: ./platform
      target: prod
    ports:
      - "8001:8000"  # Change to a different port, e.g., 8001
    restart: always
    volumes:
      - ./platform:/app/src/
    env_file:
      - next/.env
    environment:
      REWORKD_PLATFORM_HOST: XXX.XXX.XX.XX  # Specify the server IP address here
      REWORKD_PLATFORM_DB_HOST: db
      REWORKD_PLATFORM_DB_PORT: "3301"
      REWORKD_PLATFORM_DB_USER: "reworkd_platform"
      REWORKD_PLATFORM_DB_PASS: "reworkd_platform"
      REWORKD_PLATFORM_DB_BASE: "reworkd_platform"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    build:
      context: ./db
    ports:
      - "3301:3301"
    environment:
      MYSQL_DATABASE: "reworkd_platform"
      MYSQL_USER: "reworkd_platform"
      MYSQL_PASSWORD: "reworkd_platform"
      MYSQL_ROOT_PASSWORD: "reworkd_platform"
      MYSQL_TCP_PORT: 3301
    volumes:
      - db_data:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  weaviate:
    image: semitechnologies/weaviate:1.19.6
    restart: on-failure:0 # this should be 'no' or at least have ':1'
    ports:
      - "8081:8080"  # Change to a different port, e.g., 8081
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate:/var/lib/weaviate

volumes:
  weaviate:
  db_data:
```
  

and the following changes in /next/.env

```
# NextJS:
NEXT_PUBLIC_BACKEND_URL=https://my.example.com

# Next Auth config:
NEXTAUTH_URL=https://my.example.com

REWORKD_PLATFORM_FRONTEND_URL=https://my.example.com

# Database (Backend):
REWORKD_PLATFORM_DATABASE_PORT=3301

# Database (Frontend):
DATABASE_PORT=3301
```
  

and in /next/Dockerfile:

```
# Expose the port the app will run on
EXPOSE 3001
```
