### ISSUE TITLE
Error: Cannot find module '@tailwindcss/forms'

### ISSUE THREAD

**Issue by Superkikim** [reworkd/AgentGPT#716]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

Since pulling updates yerstaday, deploying should be errorless. @tailwindcss/forms should be installed automatically along with dependencies and in the right location. 

I tried pulling again right now, and it still happens.

### Current behaviour

After running `./setup.sh`, next is deployed, the `/next/.env` file is loaded, then an error message appear and tells `@tailwindcss/forms` cannot be found. 

Installing `@tailwindcss/forms` manually does not fix the issue. I've tried installing it in the root of the project, as well as in the next folder. 

## Log
```
next                 | error - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[2]!./src/styles/globals.css
next                 | Error: Cannot find module '@tailwindcss/forms'
next                 | Require stack:
next                 | - /next/tailwind.config.cjs
next                 | Import trace for requested module:
next                 | ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[2]!./src/styles/globals.css
next                 | ./src/styles/globals.css
```

### Failed to compile

```./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[2]!./src/styles/globals.css
Error: Cannot find module '@tailwindcss/forms'
Require stack:
- /next/tailwind.config.cjs
```

### Steps to reproduce

```bash
cd ~\
rm -rf AgentGPT
git clone git clone https://github.com/reworkd/AgentGPT.git
./setup.sh
```
Fill openAI API key and serp API key
Leave REPLICATE API key empty

Error message will be on the terminal

To see the WUI error message, open a browser and navigate to http://localhost:3000

The issue happens on manjaro linux (6.1.31-2-MANJARO) with node v18.16.0.
I was not able to reproduce the issue on Debian Bullseye (5.10.0-21-amd64) Node.js v18.15.0.

Any additional information to troubleshoot you need, please let know where to find it. Happy to look it up.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by awtkns** [comment]
Hi @Superkikim, this was a dependancy that was added recently. Could you confirm that your version has `@tailwindcss/formas` in the package.json? This fix for this is to likely just rebuild the frontend with `docker-compose up --build`

**Comment by Superkikim** [comment]
Hi @awtkns 

Given I delete the whole AgentGPT folder before to clone again and rebuild, I'm not sure this should be a concern. By cloning from scratch, I'm getting the latest revision. Am I not ?

**Comment by awtkns** [comment]
@Superkikim if you're not running through docker compose can you try reinstalling the dependancies with `cd next` & `npm i`?

**Comment by Superkikim** [comment]
I use docker compose for instance. I run setup.sh and select automatic setup. 

I compared both next folders in debian and manjaro. They are identical. So clearly the problem is on manjaro but I don't find where. 

I just tried to deploy as a different user, and I have the exact same error...

**Comment by Superkikim** [comment]
One thing to note is the node_modules folder is owned by root and not by the user cloning git and running setup.sh 

same for next-env.d.ts

If I remove all, clone an do manual install and using npm install && npm run dev, I deploys successfully. 

So there must be an issue with docker compose at some point.

**Comment by Superkikim** [comment]
Something I noticed is when I use docker compose, the `node_modules`folder and the `next-env.d.ts` folder are owned by root. When I do manual as explained above, these are owned my the user. 

Note that I have the same behavior on Debian yet I don't have the error message. So I don't know if it is related.

**Comment by Superkikim** [comment]
The error message is quite "clear" but I don't know where to find more verbose details: 

```
next                 | error - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[2]!./src/styles/globals.css
next                 | Error: Cannot find module '@tailwindcss/forms'
next                 | Require stack:
next                 | - /next/tailwind.config.cjs
next                 | Import trace for requested module:
next                 | ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[2]!./src/styles/globals.css
next                 | ./src/styles/globals.css
```

So far 

I have tried to run manually (next is deployed successfully)
I have tried running docker-compose --no-cache: I have the same error
I have tried to run nmp install before I run docker compose: same problem

I'm out of ideas.

**Comment by Superkikim** [comment]
Looking in inside the container, @tailwindcss/forms is missing in node_modules

Yet, it seems to be installing successfully

`#21 7.440 npm http fetch GET 200 https://registry.npmjs.org/@tailwindcss/forms/-/forms-0.5.3.tgz 5570ms (cache miss)`

**Comment by jasangill1** [comment]
Hello @Superkikim are you still dealing with this problem? If so to help us get a better grasp of the situation, could you please provide the Dockerfile you're using?

**Comment by Superkikim** [comment]
@jasangill1 Hi. I just tried to clone again the repo at `https://github.com/reworkd/AgentGPT`. Therefore the docker compose (below) should be the one from the repo.

and the error is still there:

```
next                 | error - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[2]!./src/styles/globals.css
next                 | Error: Cannot find module '@tailwindcss/forms'
next                 | Require stack:
next                 | - /next/tailwind.config.cjs
next                 | Import trace for requested module:
next                 | ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[2]!./src/styles/globals.css
next                 | ./src/styles/globals.css
```

`docker-compose.yml`

```
version: '3.9'

services:
  next:
    container_name: next
    build:
      context: ./next
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./next/.env:/next/.env
      - ./next/:/next/
      - /next/node_modules
      - /next/.next

  platform:
    container_name: platform
    build:
      context: ./platform
      target: prod
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./platform:/app/src/
    env_file:
      - next/.env
    environment:
      REWORKD_PLATFORM_HOST: 0.0.0.0
      REWORKD_PLATFORM_DB_HOST: db
      REWORKD_PLATFORM_DB_PORT: "3307"
      REWORKD_PLATFORM_DB_USER: "reworkd_platform"
      REWORKD_PLATFORM_DB_PASS: "reworkd_platform"
      REWORKD_PLATFORM_DB_BASE: "reworkd_platform"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    build:
      context: ./db
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: "reworkd_platform"
      MYSQL_USER: "reworkd_platform"
      MYSQL_PASSWORD: "reworkd_platform"
      MYSQL_ROOT_PASSWORD: "reworkd_platform"
      MYSQL_TCP_PORT: 3307
    volumes:
      - db_data:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  weaviate:
    image: semitechnologies/weaviate:1.19.6
    restart: on-failure:0
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate:/var/lib/weaviate

  docs:
    build: ./docs
    ports:
      - "3001:3001"

volumes:
  weaviate:
  db_data:
```
