### ISSUE TITLE
Sign In form does not appear in an Ubuntu 22.04 VPS docker compose setup behind a Traefik V2 proxy.

### ISSUE THREAD

**Issue by SajidK25** [reworkd/AgentGPT#990]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

I am trying to deploy docker compose setup into following VPS:-

- Contabo
- 16GB RAM 512GB storage
- Ubuntu 22.04
- Traefik proxy
- SSL

### docker-compose.yml

```
version: '3.9'

services:
  next:
    container_name: nextv09
    build:
      context: ./next
      dockerfile: Dockerfile
    ports:
      - "3009:3000"
    volumes:
      - ./next/.env:/next/.env
      - ./next/:/next/
      - /next/node_modules
      - /next/.next
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=auto-gpt.tech"
      - "traefik.http.routers.nextv09-insecure.rule=Host(`example.com`)"
      - "traefik.http.routers.nextv09-insecure.entrypoints=web"
      - "traefik.http.middlewares.nextv09-redirect-web-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.nextv09-insecure.middlewares=nextv09-redirect-web-secure"
      - "traefik.http.routers.nextv09.rule=Host(`example.com`)"
      - "traefik.http.routers.nextv09.entrypoints=websecure"
      - "traefik.http.routers.nextv09.tls=true"
      - "traefik.http.routers.nextv09.tls.certresolver=myresolver"
      - "traefik.http.services.nextv09-insecure.loadbalancer.server.port=3000"
      - "traefik.http.routers.nextv09.middlewares=nextv09_auth"
      "traefik.http.middlewares.nextv09_auth.basicauth.users=DEA:$$2y$$05$$u6owE6I3Hlmnjx6L9GiF0.Txrr022V20vsbKsUpAtWiq0VWlxn.t."
    networks:
      - auto-gpt.tech
      - default
  platform:
    container_name: platform-v09
    build:
      context: ./platform
      target: prod
    ports:
      - "8099:8000"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=auto-gpt.tech"
      - "traefik.http.routers.platform-v09-insecure.rule=Host(`backend.example.com`)"
      - "traefik.http.routers.platform-v09-insecure.entrypoints=web"
      - "traefik.http.middlewares.platform-v09-redirect-web-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.platform-v09-insecure.middlewares=platform-v09-redirect-web-secure"
      - "traefik.http.routers.platform-v09.rule=Host(`backend.example.com`)"
      - "traefik.http.routers.platform-v09.entrypoints=websecure"
      - "traefik.http.routers.platform-v09.tls=true"
      - "traefik.http.routers.platform-v09.tls.certresolver=myresolver"
      - "traefik.http.services.platform-v09-insecure.loadbalancer.server.port=8000"
    volumes:
      - ./platform:/app/src/
    env_file:
      - next/.env
    environment:
      REWORKD_PLATFORM_HOST: 0.0.0.0
      REWORKD_PLATFORM_DB_HOST: db
      REWORKD_PLATFORM_DB_PORT: "3307"
      REWORKD_PLATFORM_DB_USER: "reworkd_platform"
      REWORKD_PLATFORM_DB_PASS: "reworkd_platform"
      REWORKD_PLATFORM_DB_BASE: "reworkd_platform"
    depends_on:
      - db
    networks:
      - auto-gpt.tech
      - default

  db:
    image: mysql:8.0
    container_name: db-nextv09
    restart: always
    build:
      context: ./db
    ports:
      - "3310:3307"
    environment:
      MYSQL_DATABASE: "reworkd_platform"
      MYSQL_USER: "reworkd_platform"
      MYSQL_PASSWORD: "reworkd_platform"
      MYSQL_ROOT_PASSWORD: "reworkd_platform"
      MYSQL_TCP_PORT: 3307
    volumes:
      - db_data:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    networks:
      - default

  weaviate:
    image: semitechnologies/weaviate:1.19.6
    restart: on-failure:0
    ports:
      - "8088:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate:/var/lib/weaviate
    networks:
      - default

  docs:
    build: ./docs
    ports:
      - "3005:3001"
    networks:
      - default

volumes:
  weaviate:
  db_data:

networks:
  auto-gpt.tech:
    external: true

```
### .env
```
# Platform Config: (max loops determines how many times the agent may execute)
NEXT_PUBLIC_MAX_LOOPS="100"
REWORKD_PLATFORM_MAX_LOOPS=${NEXT_PUBLIC_MAX_LOOPS}

# Deployment Environment:
NODE_ENV="development"
NEXT_PUBLIC_VERCEL_ENV="${NODE_ENV}"

# NextJS:
NEXT_PUBLIC_BACKEND_URL="https://backend.example.com"

# Next Auth config:
NEXTAUTH_SECRET=PZLls3cExFs9znMojQAo9eYd8PyriBeYZ2SN
#NEXTAUTH_URL="http://localhost:3000"
NEXTAUTH_URL="https://example.com"
# Auth providers (Use if you want to get out of development mode sign-in):
GOOGLE_CLIENT_ID="***"
GOOGLE_CLIENT_SECRET="***"
GITHUB_CLIENT_ID="***"
GITHUB_CLIENT_SECRET="***"
DISCORD_CLIENT_SECRET="***"
DISCORD_CLIENT_ID="***"

# Backend:
REWORKD_PLATFORM_ENVIRONMENT="${NODE_ENV}"
REWORKD_PLATFORM_FF_MOCK_MODE_ENABLED="false"
REWORKD_PLATFORM_OPENAI_API_KEY="sk-jkdsdadklashdashhkahdashdhkhdakhhdkhsahdkshd"
REWORKD_PLATFORM_FRONTEND_URL="https://example.com"
REWORKD_PLATFORM_RELOAD="true"
REWORKD_PLATFORM_OPENAI_API_BASE="https://api.openai.com/v1"
REWORKD_PLATFORM_SERP_API_KEY="changeme"
REWORKD_PLATFORM_REPLICATE_API_KEY="changeme"

# Database (Backend):
REWORKD_PLATFORM_DATABASE_USER="reworkd_platform"
REWORKD_PLATFORM_DATABASE_PASSWORD="reworkd_platform"
REWORKD_PLATFORM_DATABASE_HOST="db"
REWORKD_PLATFORM_DATABASE_PORT="3307"
REWORKD_PLATFORM_DATABASE_NAME="reworkd_platform"
REWORKD_PLATFORM_DATABASE_URL="mysql://${REWORKD_PLATFORM_DATABASE_USER}:${REWORKD_PLATFORM_DATABASE_PASSWORD}@${REWORKD_PLATFORM_DATABASE_HOST}:${REWORKD_PLATFORM_DATABASE_POR>

# Database (Frontend):
DATABASE_USER="reworkd_platform"
DATABASE_PASSWORD="reworkd_platform"
DATABASE_HOST="db"
DATABASE_PORT="3307"
DATABASE_NAME="reworkd_platform"
```
### Expectation:-
 - If click on the `sign in` the Sign In form like below should be appeared
  
![001  Expected Sign in Form](https://github.com/reworkd/AgentGPT/assets/5094391/aa1b19b1-082b-401c-86cc-6dd3c3e91674)

### Sign In form not showing
![004  current behavior](https://github.com/reworkd/AgentGPT/assets/5094391/369d0620-1fd6-41a6-8bbe-679d6a86abc8)

### Error logs
![005  error logs](https://github.com/reworkd/AgentGPT/assets/5094391/4e79dc84-9c8d-42b5-a365-e21e110040d7)

### Steps to reproduce

1. From project root execute `./setup.sh`
2. Select " Docker-compose (Recommended)" when ask.
3. Go to the home page using "https://example.com".
4. Click on "Sign In" (Top-left corner)

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.
